name: AWS CD
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  DeployToAWS:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4 # Atualizado para v4

      - name: Configurar AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-action-${{ github.run_id }}

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build do Front-end (React/Vite)
        run: |
          npm install
          npm run build
        env:
          VITE_MSS_API_URL: ${{ vars.VITE_MSS_API_URL }} 

      - name: Deploy Infra e Upload via CDK
        env:
          STAGE: "dev"
          AWS_REGION: "us-east-1"
        run: |
          cd iac
          npm install
          npx cdk deploy --require-approval never
          
      # FIM! Não precisa de S3 cp nem de Cloudfront Invalidation. O CDK já fez tudo.